name: CI with Qualys WAS Scan

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install nyc for coverage
        run: npm install -g nyc

      - name: Run server tests
        run: |
          npm run test:server || echo "Server tests failed"

      - name: Run frontend tests
        run: |
          npm run test:frontend || echo "Frontend tests failed"

      - name: Copy coverage reports (if available)
        run: |
          cp build/reports/coverage/frontend-tests/lcov.info frontend-lcov.info || echo "Frontend coverage not found"
          cp build/reports/coverage/server-tests/lcov.info server-lcov.info || echo "Server coverage not found"

  qualys-was-scan:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Qualys WAS Scan
        uses: Qualys/github-action-qwas@v1.0.0
        with:
          API_SERVER: ${{ vars.API_SERVER }}
          QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
          QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
          WEBAPP_ID: ${{ vars.WEBAPP_ID }}
          SCAN_NAME: ${{ vars.SCAN_NAME }}
          SCAN_TYPE: ${{ vars.SCAN_TYPE }}
